export const AUTHENTICATED = 'AUTHENTICATED';
export const HOST_CHANGED = 'HOST_CHANGED';
export const DEVICE_CHANGED = 'DEVICE_CHANGED';
export const CONNECTION_STATE_CHANGED = 'CONNECTION_STATE_CHANGED';
export const SET_TOKEN = 'SET_TOKEN';
